# Generated by Django 6.0.1 on 2026-02-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=32)),
                ("content", models.TextField()),
                (
                    "posted",
                    models.DateTimeField(auto_now_add=True, verbose_name="posted"),
                ),
            ],
            options={
                "ordering": ["-posted"],
            },
        ),
    ]
