# Generated by Django 5.2.11 on 2026-02-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DecisionLogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                ("created_time", models.DateTimeField(verbose_name="created")),
                ("author", models.CharField(max_length=40, verbose_name="author")),
            ],
            options={
                "ordering": ["created_time"],
            },
        ),
    ]
